from psycopg2.extras import RealDictCursor
from flask import Flask, redirect, render_template, request, jsonify, url_for, session
from datetime import datetime, timezone
from werkzeug.security import check_password_hash, generate_password_hash
import os
import psycopg2
from psycopg2 import sql
import secrets
import argparse
from dotenv import load_dotenv
from create_user import admin_or_super_required_json, admin_required_json, admin_required_page, ensure_trip_prefix, get_allowed_hub_ids_for_user, is_user_allowed_for_hub, is_user_allowed_for_trip, login_required_json, login_required_page, get_current_user, create_user, superadmin_required_json, superadmin_required_page
from db import init_db
from get_conn import get_pg_conn
load_dotenv()

app = Flask(__name__)
app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')
ENC_KEY = os.environ.get("PG_ENC_KEY", "CHANGE_ME")


# ---------- Web pages ----------

def fetch_trip_hubs_from_pg(schema: str = None, table: str = None):
    schema = schema or os.environ.get("PG_SCHEMA", "public")
    table  = table  or os.environ.get("PG_TABLE", "NVT Route$0d6519c0-93fa-42a6-9b")
    trip_col = os.environ.get("PG_TRIP_COL", "Trip No_")
    hub_col  = os.environ.get("PG_HUB_COL", "Address name")

    mapping = {}
    pg = get_pg_conn()
    try:
        q = sql.SQL("SELECT {trip}, {hub} FROM {schema}.{table}").format(
            trip=sql.Identifier(trip_col),
            hub=sql.Identifier(hub_col),
            schema=sql.Identifier(schema),
            table=sql.Identifier(table),
        )
        with pg.cursor() as cur:
            cur.execute(q)
            for trip_no, hub_name in cur.fetchall():
                mapping[str(trip_no)] = str(hub_name) if hub_name is not None else None
    finally:
        pg.close()
    return mapping

def ensure_pg_admin_table():
    try:
        with get_pg_conn() as pg:
            with pg.cursor() as cur:
                # 1) pgcrypto
                cur.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

                # 2) базова таблица (без plaintext)
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS public.admin_users(
                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      username TEXT NOT NULL UNIQUE,
                      password_hash TEXT NOT NULL,
                      role TEXT NOT NULL,
                      owner_admin_username TEXT,
                      is_active BOOLEAN NOT NULL DEFAULT TRUE,
                      password_encrypted BYTEA,
                      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                      last_password_viewed_at TIMESTAMPTZ,
                      last_password_viewed_by  TEXT
                    );
                """)

                # 3) алтернативно: ако мигрираме от стара таблица – добави липсващи колони
                cur.execute("""
                    DO $$
                    BEGIN
                      IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema='public' AND table_name='admin_users' AND column_name='owner_admin_username'
                      ) THEN
                        ALTER TABLE public.admin_users ADD COLUMN owner_admin_username TEXT;
                      END IF;

                      IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema='public' AND table_name='admin_users' AND column_name='is_active'
                      ) THEN
                        ALTER TABLE public.admin_users ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
                      END IF;

                      IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema='public' AND table_name='admin_users' AND column_name='password_encrypted'
                      ) THEN
                        ALTER TABLE public.admin_users ADD COLUMN password_encrypted BYTEA;
                      END IF;

                      IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema='public' AND table_name='admin_users' AND column_name='updated_at'
                      ) THEN
                        ALTER TABLE public.admin_users ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
                      END IF;

                      -- ако все още има password_plain → отстрани го
                      IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema='public' AND table_name='admin_users' AND column_name='password_plain'
                      ) THEN
                        ALTER TABLE public.admin_users DROP COLUMN password_plain;
                      END IF;
                    END $$;
                """)
            pg.commit()
        print("[PG] admin_users ensured (schema aligned)", flush=True)
    except Exception as e:
        print("[PG] ensure_pg_admin_table error:", e, flush=True)


def pg_upsert_credential(
    username: str,
    password_plain: str | None,
    password_hash: str,
    role: str,
    owner_admin_username: str | None = None,
    is_active: bool = True,
):
    enc_key = os.environ.get("PG_ENC_KEY", "CHANGE_ME")

    if role == "superadmin":
        owner_admin_username = None

    with get_pg_conn() as pg:
        with pg.cursor() as cur:
            cur.execute("""
                INSERT INTO public.admin_users
                    (username, password_hash, role, owner_admin_username,
                     is_active, password_encrypted, created_at, updated_at)
                VALUES (
                    %s, %s, %s, %s,
                    %s,
                    CASE WHEN %s IS NOT NULL THEN pgp_sym_encrypt(%s, %s) ELSE NULL END,
                    NOW(), NOW()
                )
                ON CONFLICT (username) DO UPDATE
                   SET password_hash = EXCLUDED.password_hash,
                       role          = EXCLUDED.role,
                       owner_admin_username = COALESCE(EXCLUDED.owner_admin_username, public.admin_users.owner_admin_username),
                       is_active     = EXCLUDED.is_active,
                       password_encrypted = CASE
                           WHEN EXCLUDED.password_encrypted IS NOT NULL THEN EXCLUDED.password_encrypted
                           ELSE public.admin_users.password_encrypted
                       END,
                       updated_at    = NOW();
            """, (
                username, password_hash, role, owner_admin_username,
                is_active,
                password_plain, password_plain, enc_key
            ))
        pg.commit()


def pg_insert_session_start(username: str, order_no: str, start_ts: str):
    try:
        with get_pg_conn() as pg:
            with pg.cursor() as cur:
                cur.execute("""
                    INSERT INTO public.sessions (username, order_no, start_ts)
                    VALUES (%s, %s, %s)
                """, (username, order_no, start_ts))
            pg.commit()
    except Exception as e:
        print("[PG] insert session start error:", e, flush=True)

def pg_update_session_stop(username: str, order_no: str, end_ts: str, minutes: int):
    try:
        with get_pg_conn() as pg:
            with pg.cursor() as cur:
                cur.execute("""
                    WITH open_row AS (
                      SELECT id
                        FROM public.sessions
                       WHERE username=%s AND order_no=%s AND end_ts IS NULL
                       ORDER BY start_ts DESC
                       LIMIT 1
                    )
                    UPDATE public.sessions s
                       SET end_ts=%s, minutes=%s
                      FROM open_row
                     WHERE s.id = open_row.id
                """, (username, order_no, end_ts, minutes))
            pg.commit()
    except Exception as e:
        print("[PG] update session stop error:", e, flush=True)

def sync_trip_hubs_from_postgres():
    with get_pg_conn() as pg:
        with pg.cursor() as cur:
            # 1) Прочети източника
            cur.execute("SELECT trip_no, hub_name FROM public.trip_hubs")
            rows = cur.fetchall()
            # 2) Upsert в целевата map таблица
            for trip_no, hub_name in rows:
                # ако ползваш hub_id вместо име, адаптирай тук
                cur.execute("""
                    INSERT INTO public.trip_hub_map (trip_no, hub_id)
                    VALUES (%s, (
                        SELECT id FROM public.hubs WHERE name = %s
                    ))
                    ON CONFLICT (trip_no) DO UPDATE
                      SET hub_id = EXCLUDED.hub_id
                """, (str(trip_no), str(hub_name)))

        pg.commit()

def sync_trip_hub_map_from_bc():
    """
    Попълва/обновява public.trip_hub_map от public.bc_trips (по нормализирани имена),
    за да може приложението да вижда allowed триповете.
    """
    with get_pg_conn() as pg:
        with pg.cursor() as cur:
            cur.execute("""
                INSERT INTO public.trip_hub_map (trip_no, hub_id, trip_no_norm, address_name_norm)
                SELECT b.trip_no, h.id, b.trip_no_norm, b.address_name_norm
                FROM public.bc_trips b
                JOIN public.hubs h
                  ON h.name_norm = b.address_name_norm
                ON CONFLICT (trip_no) DO UPDATE
                  SET hub_id = EXCLUDED.hub_id,
                      trip_no_norm = EXCLUDED.trip_no_norm,
                      address_name_norm = EXCLUDED.address_name_norm;
            """)
        pg.commit()

def normalize_trip_no(s: str | None) -> str | None:
    if not s: return s
    s = s.strip()
    s = s.replace('–','-').replace('−','-').replace('‑','-')  # различни unicode тирета -> '-'
    s = s.replace('\u00A0',' ').replace('\u202F',' ')
    s = " ".join(s.split())
    return s.upper()

def ensure_trip_prefix(s: str | None) -> str | None:
    s = normalize_trip_no(s)
    if not s: return s
    if not s.startswith("TRIP-"):
        s = "TRIP-" + s.lstrip("TRIP-")
    return s


def encrypt_existing_plain_passwords():
    enc_key = os.environ.get("PG_ENC_KEY", "CHANGE_ME")
    with get_pg_conn() as pg:
        with pg.cursor() as cur:
            # криптиране на наличните plaintext пароли (ако има)
            cur.execute("""
                UPDATE public.admin_users
                   SET password_encrypted = pgp_sym_encrypt(password_plain, %s),
                       updated_at = NOW()
                 WHERE password_plain IS NOT NULL AND length(password_plain) > 0
            """, (enc_key,))
        pg.commit()
    print("Готово: password_plain е криптирана в password_encrypted.")


@app.route("/")
@login_required_page

def index():
    u = get_current_user()
    if not u:
        return redirect(url_for("do_login"))
    # оператор -> новия изглед
    if u["role"] == "user":
        return render_template("operator_home.html", user=u)
    # admin/superadmin -> към подходящи страници
    if u["role"] == "admin":
        return redirect(url_for("admin_users"))
    if u["role"] == "superadmin":
        return redirect(url_for("admin_users"))

@app.get("/login")
def login():
    return render_template("login.html")

@app.post("/login")
def do_login():
    data = request.form or {}
    username = (data.get("username") or "").strip()
    password = data.get("password") or ""

    if not username or not password:
        return render_template("login.html",
                               error="Въведи потребителско име и парола.",
                               username=username)

    # 1) Опит: public.users → допускаме само superadmin от тази таблица
    try:
        with get_pg_conn() as pg:
            with pg.cursor(cursor_factory=RealDictCursor) as cur:
                cur.execute("""
                    SELECT id, username, password_hash, role, TRUE AS is_active
                    FROM public.users
                    WHERE username = %s
                    LIMIT 1
                """, (username,))
                urow = cur.fetchone()
    except Exception as e:
        return render_template("login.html",
                               error=f"PG връзка (users): {e}",
                               username=username)

    if urow and (urow.get("role") or "").lower() == "superadmin":
        if urow.get("password_hash") and check_password_hash(urow["password_hash"], password):
            session.clear()
            session["username"]     = urow["username"]
            session["auth_source"]  = "pg"
            session["pg_table"]     = "users"          # <-- важно
            session["role"]         = "superadmin"
            session["user_id"]      = urow.get("id")
            return redirect(url_for("index"))

    # 2) Опит: public.admin_users → admin/user
    try:
        with get_pg_conn() as pg:
            with pg.cursor(cursor_factory=RealDictCursor) as cur:
                cur.execute("""
                    SELECT id, username, password_hash, role, COALESCE(is_active, TRUE) AS is_active
                    FROM public.admin_users
                    WHERE username = %s
                    LIMIT 1
                """, (username,))
                arow = cur.fetchone()
    except Exception as e:
        return render_template("login.html",
                               error=f"PG връзка (admin_users): {e}",
                               username=username)

    if arow and arow["is_active"] and arow.get("password_hash") and check_password_hash(arow["password_hash"], password):
        session.clear()
        session["username"]     = arow["username"]
        session["auth_source"]  = "pg"
        session["pg_table"]     = "admin_users"
        session["role"]         = (arow["role"] or "").lower()
        session["user_id"]      = arow.get("id")
        return redirect(url_for("index"))

    return render_template("login.html", error="Грешно потребителско име или парола.", username=username)

@app.get("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))

# Admin panel 
#now 
@app.route("/admin/users", methods=["GET", "POST"])
@admin_required_page
def admin_users():
    current = get_current_user()
    message = None

    if request.method == "POST":
        username = (request.form.get("username") or "").strip()
        password = request.form.get("password") or ""
        role_in  = (request.form.get("role") or "user").strip()

        # Ролеви правила
        if current["role"] == "admin":
            role = "user"
        else:
            role = role_in if role_in in ("user", "admin") else "user"

        # owner за НЕ-superadmin
        owner_admin_username = current["username"] if role in ("user", "admin") else None

        try:
            ph = generate_password_hash(password)

            pg_upsert_credential(
                username=username,
                password_plain=password,
                password_hash=ph,
                role=role,
                owner_admin_username=owner_admin_username,
                is_active=True
            )

            message = f"Създаден потребител: {username} (role={role})"
        except Exception as e:
            message = f"Грешка: {e}"

    # ---------- Листинг от PG ----------
    users = []
    try:
        with get_pg_conn() as pg:
            with pg.cursor(cursor_factory=RealDictCursor) as cur:
                if current["role"] == "superadmin":
                    cur.execute("""
                        SELECT username,
                            role,
                            owner_admin_username,
                            COALESCE(is_active, TRUE) AS is_active,
                            to_char(created_at AT TIME ZONE 'Europe/Sofia', 'YYYY-MM-DD HH24:MI:SS') AS created_at_fmt
                        FROM public.admin_users
                    ORDER BY CASE role
                                WHEN 'superadmin' THEN 1
                                WHEN 'admin' THEN 2
                                ELSE 3
                            END, username
                    """)
                else:
                    cur.execute("""
                        SELECT username,
                            role,
                            owner_admin_username,
                            COALESCE(is_active, TRUE) AS is_active,
                            to_char(created_at AT TIME ZONE 'Europe/Sofia', 'YYYY-MM-DD HH24:MI:SS') AS created_at_fmt
                        FROM public.admin_users
                        WHERE role='user'
                        AND owner_admin_username=%s
                        AND COALESCE(is_active, TRUE)=TRUE
                    ORDER BY username
                    """, (current["username"],))
                users = cur.fetchall()

    except Exception as e:
        message = (message or "") + f" [PG list error: {e}]"

    return render_template("admin_users.html", users=users, message=message, user=current)

# ---------- JSON helpers ----------
@app.get("/me")
def me():
    user = get_current_user()
    if not user:
        return jsonify({"ok": False}), 401
    return jsonify({"ok": True, "user": user})

# ---------- Time tracking API (мулти-таймери по поръчка) ----------

@app.post("/start")
@login_required_json
def start_timer():
    user = get_current_user()
    if user["role"] in ("admin", "superadmin"):
        return jsonify({"ok": False, "error": "Администраторът не може да стартира таймер."}), 403

    data = request.get_json() or {}
    raw = (data.get("order_no") or "").strip()
    order_no = ensure_trip_prefix(raw)
    hub_id_in = data.get("hub_id")  # може да липсва

    if not order_no:
        return jsonify({"ok": False, "error": "Въведи номер на TRIP-a."}), 400

    try:
        with get_pg_conn() as pg:
            # 1) Списък от хъбове за TRIP
            with pg.cursor() as cur:
                cur.execute("""
                    SELECT m.hub_id
                    FROM public.trip_hub_map m
                    WHERE m.trip_no = %s
                """, (order_no,))
                trip_hubs = {int(r[0]) for r in cur.fetchall() if r and r[0] is not None}

            # ако няма map – опитай live-мапинг от bc_trips + hub_aliases и кеширай
            if not trip_hubs:
                with pg.cursor() as cur:
                    cur.execute("""
                        INSERT INTO public.trip_hub_map (trip_no, hub_id)
                        SELECT DISTINCT b.trip_no, ha.hub_id
                        FROM public.bc_trips b
                        JOIN public.hub_aliases ha
                          ON ha.alias_norm = public.norm_text(b.address_name)
                        WHERE b.trip_no = %s
                        ON CONFLICT (trip_no, hub_id) DO NOTHING
                        RETURNING hub_id
                    """, (order_no,))
                    trip_hubs = {int(r[0]) for r in cur.fetchall()}

            if not trip_hubs:
                return jsonify({"ok": False, "error": "TRIP не е мапнат към нито един Хъб."}), 400

            # 2) Allowed хъбове за този user
            allowed = get_allowed_hub_ids_for_user(user)

            # 3) Определи hub_id
            hub_id: int | None = None
            if hub_id_in is not None:
                try:
                    hub_id = int(hub_id_in)
                except (TypeError, ValueError):
                    return jsonify({"ok": False, "error": "Липсва или е невалиден hub_id."}), 400
                if hub_id not in trip_hubs:
                    return jsonify({"ok": False, "error": "Този TRIP не е валиден за избрания Хъб."}), 400
                if not is_user_allowed_for_hub(pg, hub_id, user["username"], user["role"]):
                    return jsonify({"ok": False, "error": "Нямаш права за този Хъб."}), 403
            else:
                # fallback: опитай да намериш точно един allowed хъб за този TRIP
                candidates = [hid for hid in trip_hubs if hid in allowed]
                if len(candidates) == 0:
                    return jsonify({"ok": False, "error": "TRIP е мапнат, но нямаш права за нито един Хъб."}), 403
                if len(candidates) > 1:
                    return jsonify({"ok": False, "error": "TRIP е валиден за няколко Хъба. Избери конкретен Хъб."}), 400
                hub_id = int(candidates[0])

            # 4) Забрани втори активен таймер за същия TRIP+HUB от този user
            now_ts = datetime.now(timezone.utc)
            with pg.cursor() as cur:
                cur.execute("""
                    SELECT 1
                    FROM public.sessions
                    WHERE username = %s AND order_no = %s AND hub_id = %s AND end_ts IS NULL
                    LIMIT 1
                """, (user["username"], order_no, hub_id))
                if cur.fetchone():
                    return jsonify({"ok": False, "error": "Вече имаш активен таймер за този TRIP и Хъб."}), 400

                cur.execute("""
                    INSERT INTO public.sessions (order_no, hub_id, username, start_ts)
                    VALUES (%s, %s, %s, %s)
                """, (order_no, hub_id, user["username"], now_ts))
            pg.commit()

            return jsonify({"ok": True, "order_no": order_no, "hub_id": hub_id, "start_ts": now_ts.isoformat()})

    except Exception as e:
        return jsonify({"ok": False, "error": f"PG: {e}"}), 500
    
@app.post("/stop")
@login_required_json
def stop_timer():
    user = get_current_user()
    if user["role"] in ("admin", "superadmin"):
        return jsonify({"ok": False, "error": "Администраторът не може да спира таймер."}), 403

    data = request.get_json() or {}
    order_no = ensure_trip_prefix(data.get("order_no"))
    hub_id = data.get("hub_id")  # опционално

    if not order_no:
        return jsonify({"ok": False, "error": "Въведи номер на TRIP."}), 400

    now_ts = datetime.now(timezone.utc)
    try:
        with get_pg_conn() as pg:
            with pg.cursor() as cur:
                if hub_id is not None:
                    try:
                        hub_id = int(hub_id)
                    except (TypeError, ValueError):
                        return jsonify({"ok": False, "error": "Невалиден hub_id."}), 400

                    cur.execute("""
                        SELECT id
                        FROM public.sessions
                        WHERE username=%s AND order_no=%s AND hub_id=%s AND end_ts IS NULL
                        ORDER BY id DESC LIMIT 1
                    """, (user["username"], order_no, hub_id))
                    row = cur.fetchone()
                    if not row:
                        return jsonify({"ok": False, "error": "Няма активен таймер за този TRIP/Хъб."}), 400
                    sess_id = row[0]
                else:
                    cur.execute("""
                        SELECT id
                        FROM public.sessions
                        WHERE username=%s AND order_no=%s AND end_ts IS NULL
                        ORDER BY id DESC
                    """, (user["username"], order_no))
                    ids = [r[0] for r in cur.fetchall()]
                    if len(ids) == 0:
                        return jsonify({"ok": False, "error": "Няма активен таймер за този TRIP."}), 400
                    if len(ids) > 1:
                        return jsonify({"ok": False, "error": "Има няколко активни таймера за този TRIP. Посочи hub_id."}), 400
                    sess_id = ids[0]

                cur.execute("""
                    UPDATE public.sessions
                       SET end_ts = %s,
                           minutes = CASE
                                      WHEN EXTRACT(EPOCH FROM (%s - start_ts)) <= 0 THEN 0
                                      ELSE GREATEST(1, CEIL(EXTRACT(EPOCH FROM (%s - start_ts)) / 60.0))::int
                                    END
                     WHERE id = %s
                 RETURNING minutes;
                """, (now_ts, now_ts, now_ts, sess_id))
                minutes = cur.fetchone()[0]
            pg.commit()

        return jsonify({"ok": True, "order_no": order_no, "hub_id": hub_id, "end_ts": now_ts.isoformat(), "minutes": minutes})
    except Exception as e:
        return jsonify({"ok": False, "error": f"PG: {e}"}), 500

@app.get("/active")
@login_required_json
def active():
    u = get_current_user()
    if u["role"] in ("admin", "superadmin"):
        return jsonify({"ok": False, "error": "Администраторът няма активни таймери."}), 403

    try:
        with get_pg_conn() as pg:
            with pg.cursor(cursor_factory=RealDictCursor) as cur:
                cur.execute("""
                    SELECT order_no, hub_id, start_ts
                    FROM public.sessions
                    WHERE username = %s
                      AND end_ts IS NULL
                    ORDER BY start_ts DESC
                """, (u["username"],))
                rows = cur.fetchall()
    except Exception as e:
        return jsonify({"ok": False, "error": f"PG: {e}"}), 500

    return jsonify({
        "ok": True,
        "active": [
            {
                "order_no": r["order_no"],
                "hub_id":   r["hub_id"],
                "start_ts": r["start_ts"].isoformat() if r["start_ts"] else None
            } for r in rows
        ]
    })

@app.get("/report")
@admin_required_json
def report():
    current = get_current_user()
    order_no = (request.args.get("order_no") or "").strip()
    username = (request.args.get("username") or "").strip()
    group_by = (request.args.get("group_by") or "both").strip().lower()

    base_sql = """
        SELECT au.username, s.order_no, COALESCE(SUM(s.minutes), 0) AS total_minutes
        FROM public.sessions s
        JOIN public.admin_users au
          ON LOWER(au.username) = LOWER(s.username)
        WHERE 1=1
    """
    params = []

    if current["role"] == "admin":
        base_sql += " AND au.owner_admin_username = %s"
        params.append(current["username"])

    if order_no:
        base_sql += " AND s.order_no = %s"
        params.append(order_no)

    if username:
        base_sql += " AND LOWER(au.username) = LOWER(%s)"
        params.append(username)

    if group_by == "user":
        base_sql += " GROUP BY au.username ORDER BY au.username"
    elif group_by == "order":
        base_sql += " GROUP BY s.order_no ORDER BY s.order_no"
    else:
        base_sql += " GROUP BY au.username, s.order_no ORDER BY au.username, s.order_no"

    with get_pg_conn() as pg:
        with pg.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(base_sql, tuple(params))
            rows = cur.fetchall()

    results = [{"username": r["username"], "order_no": r["order_no"], "total_minutes": int(r["total_minutes"])} for r in rows]
    return jsonify({"ok": True, "results": results})

@app.get("/trips")
@login_required_json
def trips_list():
    current = get_current_user()
    q = (request.args.get("q") or "").strip()

    allowed = get_allowed_hub_ids_for_user(current)
    if current["role"] != "superadmin" and not allowed:
        return jsonify({"ok": True, "trips": []})

    sql = [
        "SELECT m.trip_no, h.id AS hub_id, h.name AS hub_name",
        "FROM public.trip_hub_map m",
        "JOIN public.hubs h ON h.id = m.hub_id",
        "WHERE 1=1"
    ]
    params = []

    if current["role"] != "superadmin":
        sql.append("AND m.hub_id = ANY(%s)")
        params.append(list(allowed))
    if q:
        sql.append("AND m.trip_no ILIKE %s")
        params.append(q + "%")

    sql.append("ORDER BY m.trip_no, h.name LIMIT 50")
    final_sql = "\n".join(sql)

    items = []
    try:
        with get_pg_conn() as pg:
            with pg.cursor() as cur:
                cur.execute(final_sql, tuple(params))
                items = [{"trip_no": r[0], "hub_id": r[1], "hub_name": r[2]} for r in cur.fetchall()]
    except Exception as e:
        return jsonify({"ok": False, "error": f"PG: {e}"}), 500

    return jsonify({"ok": True, "trips": items})

@app.get("/history")
@login_required_json
def history():
    """Историята е достъпна за администратори и суперaдмин (операторите не виждат минали сесии)."""
    current = get_current_user()
    if current["role"] not in ("admin", "superadmin"):
        return jsonify({"ok": False, "error": "Само администратор/суперадмин има достъп до история."}), 403
    # Данните се взимат през /admin/history_data
    return jsonify({"ok": True, "results": []})  # не показваме нищо тук; истинските данни са през /admin/history_data

@app.get("/admin/history")
@admin_required_page
def admin_history_page():
    user = get_current_user()
    return render_template("admin_history.html", user=user)

@app.get("/admin/history_data")
@admin_or_super_required_json
def admin_history_data():
    current = get_current_user()
    order_no = (request.args.get("order_no") or "").strip()
    username = (request.args.get("username") or "").strip()
    from_d   = (request.args.get("from") or "").strip()
    to_d     = (request.args.get("to") or "").strip()

    is_super = (current["role"] == "superadmin")

    # 1) allowed hubs за admin (superadmin няма нужда)
    allowed_hub_ids = None
    if not is_super:
        try:
            with get_pg_conn() as pg:
                with pg.cursor() as cur:
                    cur.execute("""
                        SELECT ha.hub_id
                        FROM public.hubs_admins ha
                        WHERE LOWER(ha.admin_username) = LOWER(%s)
                    """, (current["username"],))
                    allowed_hub_ids = [int(r[0]) for r in cur.fetchall() if r and r[0] is not None]
        except Exception as e:
            return jsonify({"ok": False, "error": f"PG (hubs_admins): {e}"}), 500

        if not allowed_hub_ids:
            return jsonify({"ok": True, "results": []})

    # 2) Основна заявка:
    # - JOIN hubs по sessions.hub_id (ако го има)
    # - LATERAL инференция на hub, когато s.hub_id е NULL
    # - Филтър за admin: или s.hub_id ∈ allowed, или inferred ∈ allowed
    parts = [
        "SELECT",
        "  s.username,",
        "  s.order_no,",
        "  to_char(s.start_ts AT TIME ZONE 'Europe/Sofia','YYYY-MM-DD') AS start_day,",
        "  to_char(s.start_ts AT TIME ZONE 'Europe/Sofia','HH24:MI:SS') AS start_time,",
        "  to_char(s.end_ts   AT TIME ZONE 'Europe/Sofia','YYYY-MM-DD') AS end_day,",
        "  to_char(s.end_ts   AT TIME ZONE 'Europe/Sofia','HH24:MI:SS') AS end_time,",
        "  s.minutes,",
        "  COALESCE(h.name, inf.name) AS hub_display,",
        "  COALESCE(s.hub_id, inf.id) AS hub_id_display",
        "FROM public.sessions s",
        "JOIN public.admin_users au ON LOWER(au.username) = LOWER(s.username)",
        "LEFT JOIN public.hubs h ON h.id = s.hub_id",
        # инференция: ако hub_id липсва → вземи един hub от trip_hub_map
        "LEFT JOIN LATERAL (",
        "  SELECT h2.id, h2.name",
        "  FROM public.trip_hub_map m2",
        "  JOIN public.hubs h2 ON h2.id = m2.hub_id",
        "  WHERE m2.trip_no = s.order_no",
        "    AND s.hub_id IS NULL",
        # за admin ограничаваме инференцията в allowed списъка:
        ("    AND m2.hub_id = ANY(%s)" if not is_super else ""),
        "  ORDER BY h2.id",
        "  LIMIT 1",
        ") inf ON TRUE",
    ]
    where = []
    params = []

    # параметри за инференцията (само за admin)
    if not is_super:
        params.append(list(allowed_hub_ids))

    # UI филтри
    if order_no:
        order_no = ensure_trip_prefix(order_no)
        where.append("s.order_no = %s")
        params.append(order_no)

    if username:
        where.append("LOWER(s.username) = LOWER(%s)")
        params.append(username)

    if from_d:
        where.append("DATE(s.start_ts) >= %s")
        params.append(from_d)

    if to_d:
        where.append("DATE(s.start_ts) <= %s")
        params.append(to_d)

    # филтър за admin: включи само allowed записи
    if not is_super:
        where.append("("
                     " (s.hub_id IS NOT NULL AND s.hub_id = ANY(%s))"
                     " OR "
                     " (s.hub_id IS NULL AND inf.id IS NOT NULL)"
                     ")")
        params.append(list(allowed_hub_ids))

    sql = "\n".join(parts)
    if where:
        sql += "\nWHERE " + " AND ".join(where)
    sql += "\nORDER BY s.start_ts DESC\nLIMIT 500"

    try:
        with get_pg_conn() as pg:
            with pg.cursor(cursor_factory=RealDictCursor) as cur:
                cur.execute(sql, tuple(params) if params else None)
                rows = cur.fetchall()
    except Exception as e:
        # Диагностика
        print("[SQL DEBUG] -------------------------")
        print(sql)
        print("params:", params)
        return jsonify({"ok": False, "error": str(e)}), 500

    results = [{
        "username":   r["username"],
        "order_no":   r["order_no"],
        "hub":        r["hub_display"],
        "start_day":  r["start_day"],
        "start_time": r["start_time"],
        "end_day":    r["end_day"],
        "end_time":   r["end_time"],
        "minutes":    r["minutes"],
        "hub_id":     r["hub_id_display"],
    } for r in rows]
    return jsonify({"ok": True, "results": results})

@app.post("/admin/sync_trip_hubs")
@admin_required_page
def admin_sync_trip_hubs():
    current = get_current_user()
    if current["role"] != "superadmin":
        return redirect(url_for("admin_users"))

    try:
        sync_trip_hub_map_from_bc()   # без аргументи – така е дефинирана
        msg = "Синхронизацията Trip→Hub завърши успешно."
    except Exception as e:
        msg = f"Грешка при синхронизация: {e}"

    # покажи admin_users от правилната таблица:
    users = []
    try:
        with get_pg_conn() as pg:
            with pg.cursor(cursor_factory=RealDictCursor) as cur:
                cur.execute("""
                    SELECT username, role, owner_admin_username,
                           COALESCE(is_active, TRUE) AS is_active,
                           to_char(created_at AT TIME ZONE 'Europe/Sofia','YYYY-MM-DD HH24:MI:SS') AS created_at_fmt
                    FROM public.admin_users
                    ORDER BY CASE role WHEN 'superadmin' THEN 1 WHEN 'admin' THEN 2 ELSE 3 END, username
                """)
                users = cur.fetchall()
    except Exception as e:
        msg += f" [PG list error: {e}]"

    return render_template("admin_users.html", users=users, message=msg, user=current)

@app.get("/admin/credentials")
@superadmin_required_page
def admin_credentials_page():
    rows = []
    try:
        with get_pg_conn() as pg:
            with pg.cursor() as cur:
                cur.execute("""
                    SELECT username, role, password_plain, password_hash, created_at
                      FROM public.admin_users
                  ORDER BY created_at DESC, username ASC
                """)
                rows = cur.fetchall()
    except Exception:
        rows = []
    return render_template("admin_credentials.html", rows=rows, user=get_current_user(), message=request.args.get("msg"))


@app.get("/admin/credentials/view")
@superadmin_required_json
def admin_view_password():
    """Връща текущата парола (декриптирана) за user в admin_users. Само суперaдмин."""
    enc_key = os.environ.get("PG_ENC_KEY", "CHANGE_ME")
    username = (request.args.get("username") or "").strip()
    if not username:
        return jsonify({"ok": False, "error": "Липсва username."}), 400

    try:
        with get_pg_conn() as pg:
            with pg.cursor() as cur:
                cur.execute("""
                    SELECT
                      CASE
                        WHEN password_encrypted IS NULL THEN NULL
                        ELSE pgp_sym_decrypt(password_encrypted, %s)
                      END AS password_plain
                    FROM public.admin_users
                    WHERE username = %s
                    LIMIT 1
                """, (enc_key, username))
                row = cur.fetchone()
                if not row:
                    return jsonify({"ok": False, "error": "Няма такъв потребител."}), 404
                plain = row[0]

                # лог: кой и кога е гледал паролата
                cur.execute("""
                    UPDATE public.admin_users
                       SET last_password_viewed_at = NOW(),
                           last_password_viewed_by  = %s
                     WHERE username = %s
                """, (get_current_user()["username"], username))
            pg.commit()

        return jsonify({"ok": True, "username": username, "password": plain})
    except Exception as e:
        return jsonify({"ok": False, "error": f"PG: {e}"}), 500


@app.post("/admin/users/delete")
@superadmin_required_json
def delete_user():
    current = get_current_user()
    data = request.get_json() or {}
    username = (data.get("username") or "").strip()
    with_history = bool(data.get("with_history", False))

    if not username:
        return jsonify({"ok": False, "error": "Посочи username."}), 400
    if username == current["username"]:
        return jsonify({"ok": False, "error": "Не можеш да изтриеш своя акаунт."}), 400

    # забрана за изтриване на друг superadmin (ако имаш повече от един)
    with get_pg_conn() as pg:
        with pg.cursor() as cur:
            cur.execute("SELECT role FROM public.admin_users WHERE username=%s", (username,))
            r = cur.fetchone()
            if not r:
                return jsonify({"ok": False, "error": "Няма такъв потребител."}), 404
            if r[0] == "superadmin":
                return jsonify({"ok": False, "error": "Не може да се трие superadmin."}), 403

    try:
        with get_pg_conn() as pg:
            with pg.cursor() as cur:
                if with_history:
                    cur.execute("DELETE FROM public.sessions WHERE username = %s", (username,))
                cur.execute("DELETE FROM public.admin_users WHERE username = %s", (username,))
            pg.commit()
        return jsonify({"ok": True, "deleted": username, "with_history": with_history})
    except Exception as e:
        return jsonify({"ok": False, "error": f"PG: {e}"}), 500

@app.post("/admin/users/rename")
@superadmin_required_json
def rename_user():
    current = get_current_user()
    data = request.get_json() or {}
    old_username = (data.get("old_username") or "").strip()
    new_username = (data.get("new_username") or "").strip()

    if not old_username or not new_username:
        return jsonify({"ok": False, "error": "Посочи old_username и new_username."}), 400
    if old_username == current["username"]:
        return jsonify({"ok": False, "error": "Не може да преименуваш своя акаунт оттук."}), 400

    with get_pg_conn() as pg:
        with pg.cursor() as cur:
            cur.execute("SELECT role FROM public.admin_users WHERE username=%s", (old_username,))
            r = cur.fetchone()
            if not r:
                return jsonify({"ok": False, "error": "Няма такъв потребител."}), 404
            if r[0] == "superadmin":
                return jsonify({"ok": False, "error": "Не може да се преименува superadmin."}), 403
            cur.execute("SELECT 1 FROM public.admin_users WHERE username=%s", (new_username,))
            if cur.fetchone():
                return jsonify({"ok": False, "error": "Новото потребителско име е заето."}), 400

        # транзакция: преименуваме потребителя и историята
        with pg.cursor() as cur:
            cur.execute("""
                UPDATE public.admin_users
                   SET username = %s, updated_at = NOW()
                 WHERE username = %s
            """, (new_username, old_username))
            cur.execute("""
                UPDATE public.sessions
                   SET username = %s
                 WHERE username = %s
            """, (new_username, old_username))
        pg.commit()

    return jsonify({"ok": True, "old_username": old_username, "new_username": new_username})



@app.post("/admin/users/reset_password")
@superadmin_required_json
def admin_reset_password():
    data = request.get_json(silent=True) or {}
    username = (data.get("username") or "").strip()

    if not username:
        return jsonify({"ok": False, "error": "Липсва username."}), 400

    # ВАЖНО: разграничаваме 'ключът липсва' и 'ключът е празен'
    has_new = ("new_password" in data)
    new_plain = (data.get("new_password") or "")
    new_plain = new_plain.strip()

    if has_new:
        # Подал си парола → ползваме точно нея (валидирай минимално)
        if len(new_plain) < 5:
            return jsonify({"ok": False, "error": "Паролата трябва да е поне 6 символа."}), 400
    else:
        # Не си подала парола → генерираме
        new_plain = secrets.token_urlsafe(12)

    new_hash = generate_password_hash(new_plain)
    enc_key  = os.environ.get("PG_ENC_KEY", "CHANGE_ME")

    try:
        with get_pg_conn() as pg:
            with pg.cursor() as cur:
                cur.execute("""
                    UPDATE public.admin_users
                       SET password_hash      = %s,
                           password_encrypted = pgp_sym_encrypt(%s, %s),
                           updated_at         = NOW()
                     WHERE LOWER(username) = LOWER(%s)
                 RETURNING username
                """, (new_hash, new_plain, enc_key, username))
                r = cur.fetchone()
                if not r:
                    return jsonify({"ok": False, "error": "Няма такъв потребител."}), 404
            pg.commit()

        # Винаги връщаме каква парола е активирана (ако е генерирана – я виждаш; ако е подадена – потвърждаваме)
        return jsonify({"ok": True, "username": username, "new_password": new_plain})
    except Exception as e:
        return jsonify({"ok": False, "error": f"PG: {e}"}), 500



@app.get("/debug/perm")
@login_required_json
def debug_perm():
    u = get_current_user()
    order_no = ensure_trip_prefix((request.args.get("order_no") or "").strip())

    with get_pg_conn() as pg:
        with pg.cursor() as cur:
            cur.execute("SELECT hub_id FROM public.trip_hub_map WHERE trip_no=%s LIMIT 1", (order_no,))
            r = cur.fetchone()
    trip_hub_id = int(r[0]) if r and r[0] is not None else None

    allowed = get_allowed_hub_ids_for_user(u)
    return jsonify({
        "ok": True,
        "user": u,
        "order_no": order_no,
        "trip_hub_id": trip_hub_id,
        "allowed": sorted(list(allowed)),
        "in_allowed": (trip_hub_id in allowed) if trip_hub_id is not None else False
    })

@app.get("/debug/pginfo")
def debug_pginfo():
    try:
        with get_pg_conn() as pg:
            with pg.cursor() as cur:
                cur.execute("""
                    SELECT current_database(), current_schema(),
                           inet_server_addr(), inet_server_port(), version()
                """)
                db, schema, host, port, ver = cur.fetchone()
        return jsonify({
            "ok": True,
            "database": db,
            "schema": schema,
            "host": str(host),  # важно: host може да е ::1 (IPv6) или 127.0.0.1 (IPv4)
            "port": port,
            "version": ver
        })
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 500

# ---------- Entry point ----------
def main():
    parser = argparse.ArgumentParser(description="Time Tracker")
    parser.add_argument("--create-user", action="store_true", help="Създай потребител (само от админ през терминал)")
    parser.add_argument("--username", type=str)
    parser.add_argument("--password", type=str)
    parser.add_argument("--role", type=str, default="user", help="user|admin")
    parser.add_argument("--host", type=str, default="0.0.0.0")
    parser.add_argument("--port", type=int, default=5000)
    args = parser.parse_args()

    init_db()
    ensure_pg_admin_table()
    # ensure_users_soft_delete_columns()

    if args.create_user:
        if not args.username or not args.password:
            # print("Използване: python app.py --create-user --username elitsa --password **** [--role admin]")
            return
        create_user(args.username, args.password, args.role)
        print(f"Създаден потребител: {args.username} ({args.role})")
        return

    app.run(host=args.host, port=args.port, debug=True)

if __name__ == "__main__":
    main()
